networks:
  default:

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ../volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=Upskill
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    networks: 
      - default
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  eventstore:
    container_name: eventstore
    image: ghcr.io/eventstore/eventstore:21.10.0-alpha-arm64v8
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    networks:
      - default
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    ports:
      - 9200:9200/tcp
    environment:
      - discovery.type=single-node
    
  commands:
    container_name: afranczak-commands
    image: ${DOCKER_REGISTRY-}afranczak-commands
    build:
      context: .
      dockerfile: ./Commands.Dockerfile
    ports:
      - "5010:80"
    depends_on:
      - postgres
      - eventstore
    networks:
      - default
  
  queries:
    container_name: afranczak-queries
    image: ${DOCKER_REGISTRY-}afranczak-queries
    build:
      context: .
      dockerfile: ./Queries.Dockerfile
    ports:
      - "5020:80"
    depends_on:
      - postgres
    networks:
      - default
  
  #will exit if sns is not running
  listener:
    container_name: afranczak-listener
    image: ${DOCKER_REGISTRY-}afranczak-listener
    build:
      context: .
      dockerfile: ./Listener.Dockerfile
    ports:
      - "5030:80"
    depends_on:
      - eventstore
    networks:
      - default