name: CICD

on:
  workflow_dispatch:
    inputs:
      image-tag:
        required: true
        type: string
      dockerfile:
        required: true
        default: 'Commands'
        type: choice
        options:
        - 'Commands'
        - 'Listener'
        - 'Projections'
        - 'Queries'
        
jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      fail-fast: true
    steps:

      - run: echo "REPO_NAME=${{ github.event.inputs.dockerfile,, }}" >> $GITHUB_ENV
      
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME_ARN }}
          role-session-name: ${{ secrets.AWS_OWNER }}-session
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
      
      - run: echo ${{ steps.login-ecr.outputs.registry }}

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_OWNER }}-${{ env.REPO_NAME }}
          IMAGE_TAG: ${{ github.event.inputs.image-tag }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f ${{ github.event.inputs.dockerfile }}.Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
